// <auto-generated />
using System;
using AB.AC.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AB.AC.MyAirport.EF.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20200401084713_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AB.AC.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("ID_BAGAGE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSE")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CODE_IATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_CREATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESTINATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESCALE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID_VOL")
                        .HasColumnType("int");

                    b.Property<byte?>("PRIORITAIRE")
                        .HasColumnType("tinyint");

                    b.Property<string>("SSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STA")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID_BAGAGE");

                    b.HasIndex("ID_VOL");

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("AB.AC.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("ID_VOL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CIE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DHC")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PAX")
                        .HasColumnType("int");

                    b.Property<string>("PKG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_VOL");

                    b.ToTable("Vols");
                });

            modelBuilder.Entity("AB.AC.MyAirport.EF.Bagage", b =>
                {
                    b.HasOne("AB.AC.MyAirport.EF.Vol", "Vol")
                        .WithMany("Bagages")
                        .HasForeignKey("ID_VOL");
                });
#pragma warning restore 612, 618
        }
    }
}
